### ISSUE TITLE
Write script to re-compile manim files and move to website

### ISSUE THREAD

**Issue by hschafer** [hschafer/CSE-STAT-416-book#3]

**Comment by hschafer** [comment]
@Rockett8855 Is this something you are actually working on? Just want to double-check because Josh is also joining to help with some stuff and I told him you already started this. 

Maybe you can assign yourself this task to claim it?

**Comment by hschafer** [comment]
Just noting since I ran into a problem with this. If we are going to make modules that we import (e.g., shared code), our build system will need to modify the `PYTHONPATH`. 

Right now I have 
```py
# data.py

# Some constants I want to use in other places
```

```py
# model.py
from data import *

# Manim code that uses things defined in data
```

If you just run 
```
manim model.py Model -pls
```
It will break because it doesn't know what data is. To fix this, I have to run

```
PYTHONPATH=. manim model.py Model -pls
```

**Comment by Rockett8855** [comment]
This was finished in #34
